<a href="https://colab.research.google.com/github/Laxmi-404/Deep-Learning/blob/main/DL1_BASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !conda install pytorch torchvision -c pytorch

In [ ]:
import torch

PyTorch is a library for processing tensors.A tensor is a a number,matrix,vector or n-dimensional array.

In [ ]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [ ]:
# 4.=4.0(floating point no)

In [ ]:
t1.dtype
# int 64 for 4

torch.float32

Vector:array or list of number

In [ ]:
t2=torch.tensor([1.,2,3,4])

In [ ]:
t2

tensor([1., 2., 3., 4.])

Tensors require their number to have similar datatype.

In [ ]:
# Matrix
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

Regurality of data needs to be mantained.

In [ ]:
# t4=torch.tensor([[[11,12,13],[14,15]],[[15,16,17],[17,18,19]]])
# list ke andar ke andar element equal no ke hone chahiye!:REGULARITY
# 3d array
t4=torch.tensor([[[11,12,13],[14,15,16]],[[15,16,17],[17,18,19]]])
t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[15, 16, 17],
         [17, 18, 19]]])

Tensors can have any no of dimensions and different length along each dimension.

get length: .shape property

In [ ]:
print(t1)
t1.shape
# scaler:empty array having no dimensions

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape
# list mei no of elements

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

In [ ]:
# Creating Tensors:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
m=torch.tensor([[2,3.],[4,5]],requires_grad=True)
d=torch.tensor([[[2,3.],[4,5]]])
c=torch.tensor([[[2,3.,7],[4,5,9]],[[10.,7.,5],[8.,6,3]]])
# Only Tensors of floating point and complex dtype can require gradients

In [ ]:
# Arithmetic Operation:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
z=1*y+m
z

tensor([[19., 20.],
        [21., 22.]], grad_fn=<AddBackward0>)

In [ ]:
z=1*m+m
z

tensor([[ 4.,  6.],
        [ 8., 10.]], grad_fn=<AddBackward0>)

In [ ]:
# w=c*z+d
# w
# The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

We can automatically compoute the derivative of requires_grad=True.

In [ ]:
y.backward()
# Compute derivatives

In [ ]:
# m.backward()
# grad can be implicitly created only for scalar outputs
f=(m**2).sum()
f

tensor(54., grad_fn=<SumBackward0>)

In [ ]:
# Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)
print('dy/dm:',f.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
dy/dm: None


<ipython-input-21-5847c92d926b>:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print('dy/dm:',f.grad)


The grad is gradient,another term for derivatives.

A matrix is a special type of tensor.Tensor can be a vector,number,3 dimensional array.

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# Convert from numpy array to torch tensor
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [ ]:
# Convert a torch tensor to a numpy array
z=y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [ ]:
w=torch.tensor([3.])
x=torch.tensor([4.])
b=torch.tensor([5.])
y=w*x+b
y

tensor([17.])

In [ ]:
y.shape

torch.Size([1])

Torch is the library and tensor is data structure(mathematical)

In [ ]:
# t5=torch.tensor("Hi")
# new(): invalid data type 'str'

In [ ]:
import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
# Linear Regression:

In a linear regression model,each target variable is estimated to be weighted sum of the input variables,offset by some constant,bias:

yield_apple=w11*temp+w12*humidity+w13*rainfall

yield_orange=w21*temp+w22*humidity+w23*rainfall

The learning part is:to figure out set of weights by training data to make aacurate predictions for new data by optimization technique called as gradient descent.

In [ ]:
import numpy as np
import torch

In [ ]:
# Input(temp,rainfall,humidity)
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')

In [ ]:
# Targets(apples,oranges)
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

We have created numpy arrays bcoz data csv files or numpy array form mei hota h.

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.2203, -2.0167,  0.0845],
        [ 2.0128, -0.2459, -1.7013]], requires_grad=True)
tensor([ 0.1941, -1.4608], requires_grad=True)


torch.randn creates a tensor with given shape with elements picked randomly from a normal distribution of mean 0 and standard deviation 1.

In [ ]:
# x*transpose(w)+b
def model(x):
  return x @ w.t()+b

@ represents matrix multiplication and .t means transpose of matrix.

In [ ]:
preds=model(inputs)
print(preds)
# negative preds mean?

tensor([[-115.2152,   55.8450],
        [-151.8277,   51.1853],
        [-245.9853,   42.0325],
        [ -60.9331,  130.3241],
        [-172.3003,   -5.2706]], grad_fn=<AddBackward0>)


In [ ]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
diff=preds-targets
torch.sum(diff*diff)/diff.numel()
# diff.numel() gives no of elements in diff(tensor)
# This is called mean squared error....

tensor(33451.5391, grad_fn=<DivBackward0>)

In [ ]:
# high the loss,worse the model

We need a way to evaluate our model:mean squared error:
Calculate the difference between the two matrices.

Square all the elements of difference matrix to remove negative values.

Calculate the average of resulting matrix.

In [ ]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
loss=mse(preds,targets)
loss

tensor(33451.5391, grad_fn=<DivBackward0>)

On average,off by 145 in range 50 to 200,bad model? YUPSSS


In [ ]:
# Loss is function of weights.As we change weight,loss changes
loss.backward()
# inputs and targets are not changing,so no requires_grad=True
# Here weights and biases are changing,so finding requires_grad=True(change hoga toh hi derivative niklega)
# loss.backward() karne se torch knows that you are using all of these internally as tensors. The gradients are stored in .grad property of the tensors.

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.2203, -2.0167,  0.0845],
        [ 2.0128, -0.2459, -1.7013]], requires_grad=True)
tensor([[-18578.9316, -22172.6484, -13154.3838],
        [ -2507.2480,  -5087.7534,  -2863.7744]])


The gradient indicates the rate of change of the loss.

The loss is quadratic fn of our weights and biases.

If gradient element is positive:(slope positive dir)

1.   increasing: The elements value slightly increase the loss.

2. decreasing:The elements value decrease the loss.



If gradient element is negative:slope downwards(derivative negative):

1.   increasing: The elements value slightly decrease the loss.

2. decreasing:The elements value increase the loss.


Th idea is that we are going opposite to the direction of derivatives.

positive der:decrease weight,

negative:increase weight

The increase or decrease in loss by changing a weight element is proportional to change the gradient of the loss wrt that element.

In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


PyTorch accumulates,gradients i.e the next time .grad is called,purana .grad value is added. so .zero_() set kardo.

In [ ]:
w,b

(tensor([[ 0.2203, -2.0167,  0.0845],
         [ 2.0128, -0.2459, -1.7013]], requires_grad=True),
 tensor([ 0.1941, -1.4608], requires_grad=True))

In [ ]:
# Using Gradient descent optimization algorithm
# 1.Generate predictions
# 2.calculate the loss
# 3.Compute gradients wrt w an b
# 4.Adjust the weights by subtracting a small quantity proportional to the gradient
# 5.Reset the gradients to zero

In [ ]:
preds=model(inputs)
preds

tensor([[-115.2152,   55.8450],
        [-151.8277,   51.1853],
        [-245.9853,   42.0325],
        [ -60.9331,  130.3241],
        [-172.3003,   -5.2706]], grad_fn=<AddBackward0>)

In [ ]:
loss=mse(preds,targets)
loss

tensor(33451.5391, grad_fn=<DivBackward0>)

In [ ]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-18578.9316, -22172.6484, -13154.3838],
        [ -2507.2480,  -5087.7534,  -2863.7744]])
tensor([-225.4523,  -37.1767])


In [ ]:
# Adjust the weights and reset gradients
with torch.no_grad():
  w -=w.grad* 1e-5
  b -=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

We use torch.no_grad() to indicate PyTorch that we should not track,calculate,modify grad while updating w and b.

not much decrease,just small decrease in downhill direction of grad(learning rate of algo,here 10^-5)


In [ ]:
print(w)
print(b)

tensor([[ 0.4060, -1.7950,  0.2160],
        [ 2.0379, -0.1950, -1.6726]], requires_grad=True)
tensor([ 0.1963, -1.4605], requires_grad=True)


In [ ]:
preds=model(inputs)
loss=mse(preds,targets)
loss

tensor(23884.9668, grad_fn=<DivBackward0>)

In [ ]:
# Train this like multiple epochs(iterations)
# for i in range(200):
for i in range(100):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w -=w.grad*1e-5
    b -=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

# with same no of iterations why lossdecreasing more and more each tiime

If you're running the same code multiple times without resetting the model parameters or gradients between runs, the model could accumulate updates over successive runs. This could cause the loss to decrease more and more as you're effectively continuing training over previously trained parameters without restarting from an initial state.

what if it stops at local minima rather than absolute minima?

just try initially with small learning rate,make it more small try with that too...

In [ ]:
loss

tensor(1363.5150, grad_fn=<DivBackward0>)

In [ ]:
preds

tensor([[ 66.9038,  82.8401],
        [ 92.0227,  93.6669],
        [ 80.7131, 128.7360],
        [ 77.8146, 109.7119],
        [ 85.9291,  64.2428]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
import torch.nn as nn

In [ ]:
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],
                [102,43,37],[69,96,70],[73,67,43],
                [91,88,64],[87,134,58],[102,43,37],
                [69,96,70],[73,67,43],[91,88,64],
                [87,134,58],[102,43,37],[69,96,70]],dtype='float32')

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
targets=np.array([[ 56.,  70.],[ 81., 101.], [119., 133.],
                  [ 22.,  37.],[103., 119.],[ 56.,  70.],
                  [ 81., 101.],[119., 133.],[ 22.,  37.],
                  [103., 119.],[ 56.,  70.],[ 81., 101.],
                  [119., 133.],  [ 22.,  37.], [103., 119.]],dtype='float32')

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

We are using TensorDataset which allows access to rows from inputs and targets as tuples.

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
# Define dataset
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

1000s of rows data,modeling slow,batch size used...

In [ ]:
# Define data loader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

more randomness:generalization:loss reduction fast

In [ ]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  # b for batch

tensor([[73., 67., 43.],
        [91., 88., 64.],
        [73., 67., 43.],
        [69., 96., 70.],
        [73., 67., 43.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [ 56.,  70.],
        [103., 119.],
        [ 56.,  70.]])
tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [119., 133.],
        [119., 133.],
        [ 81., 101.]])
tensor([[102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.]])
tensor([[ 22.,  37.],
        [ 22.,  37.],
        [119., 133.],
        [103., 119.],
        [103., 119.]])


In [ ]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [103., 119.],
        [119., 133.],
        [ 56.,  70.]])


In [ ]:
# Define model
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3861,  0.0886, -0.2108],
        [-0.2006,  0.0237,  0.4153]], requires_grad=True)
Parameter containing:
tensor([-0.3723,  0.2159], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3861,  0.0886, -0.2108],
         [-0.2006,  0.0237,  0.4153]], requires_grad=True),
 Parameter containing:
 tensor([-0.3723,  0.2159], requires_grad=True)]

PyTorch models require .parameters method returning a list containing all w and b matrices in model.

In [ ]:
preds=model(inputs)
preds

tensor([[24.6844,  5.0205],
        [29.0682, 10.6294],
        [32.8629, 10.0286],
        [35.0198, -3.8557],
        [20.0181, 17.7229],
        [24.6844,  5.0205],
        [29.0682, 10.6294],
        [32.8629, 10.0286],
        [35.0198, -3.8557],
        [20.0181, 17.7229],
        [24.6844,  5.0205],
        [29.0682, 10.6294],
        [32.8629, 10.0286],
        [35.0198, -3.8557],
        [20.0181, 17.7229]], grad_fn=<AddmmBackward0>)

In [ ]:
# Import nn.functional
import torch.nn.functional as F
# mse_loss

The nn.functional package contains many useful loss functions and several other utilities.

In [ ]:
loss_fn=F.mse_loss

In [ ]:
loss=loss_fn(model(inputs),targets)
loss

tensor(5759.0063, grad_fn=<MseLossBackward0>)

Instead of manually manipulating the models weoght and bias, we can use optim.SGD(STOCHASTIC GRADIENT DESCENT):stochastic becoz samples are selected in batches (with random shuffling) instead of single group.

lr:learning rate

In [ ]:
# Define optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
# Utility function to train the model:
def fit(num_epochs,model,loss_fn,opt,train_dl):
  # Repeat for given number of epochs
  for epoch in range(num_epochs):
    # Train eith batch of data
    for xb,yb in train_dl:
      # Generate preds
      preds=model(xb)
      loss=loss_fn(preds,yb)
      # Compute gradient
      loss.backward()
      # Update parameters using gradients
      opt.step()
      # it has got w andb so w=w-w*lr
      # Reset grad to zero
      opt.zero_grad()

      # print the progress
      if (epoch+1)%10 ==0:
        print('Epoch [{}/{}],Loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))


After computing the gradients using loss.backward(), opt.step() is called to update the parameters of the model based on the gradients. It uses the gradients to adjust the parameters in the direction that minimizes the loss.


epoch + 1: This is just to ensure the epoch count starts from 1, instead of 0 (common practice in training loops to start counting from 1).

num_epochs: Total number of epochs you are training for.

loss.item(): This method is used to retrieve the scalar value of the loss from the tensor. You can't print a tensor directly, so you call .item() to get the scalar value.


if (epoch + 1) % 10 == 0::

 This condition checks if the current epoch is a multiple of 10, so it will print the loss every 10th epoch (i.e., epoch 10, 20, 30, ...).

print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch + 1, num_epochs, loss.item())):

This prints the epoch number, the total number of epochs, and the loss value. The "{:.4f}" formatting ensures the loss is printed with 4 decimal places.

In [ ]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100],Loss:455.2126
Epoch [10/100],Loss:361.8072
Epoch [10/100],Loss:400.8440
Epoch [20/100],Loss:398.3780
Epoch [20/100],Loss:191.9667
Epoch [20/100],Loss:300.3520
Epoch [30/100],Loss:179.6232
Epoch [30/100],Loss:302.6955
Epoch [30/100],Loss:151.5550
Epoch [40/100],Loss:229.4061
Epoch [40/100],Loss:59.3340
Epoch [40/100],Loss:141.6337
Epoch [50/100],Loss:103.1442
Epoch [50/100],Loss:74.5330
Epoch [50/100],Loss:132.5193
Epoch [60/100],Loss:48.2525
Epoch [60/100],Loss:104.5878
Epoch [60/100],Loss:72.6896
Epoch [70/100],Loss:49.0180
Epoch [70/100],Loss:56.6200
Epoch [70/100],Loss:68.0895
Epoch [80/100],Loss:23.0893
Epoch [80/100],Loss:22.9581
Epoch [80/100],Loss:83.1942
Epoch [90/100],Loss:2.9493
Epoch [90/100],Loss:33.7041
Epoch [90/100],Loss:71.4238
Epoch [100/100],Loss:17.6078
Epoch [100/100],Loss:13.5700
Epoch [100/100],Loss:51.3335


In [ ]:
# generate preds
preds=model(inputs)
preds

tensor([[ 58.9063,  71.1603],
        [ 79.6266, 100.1607],
        [121.9550, 132.6272],
        [ 31.0331,  41.7389],
        [ 91.5363, 115.5469],
        [ 58.9063,  71.1603],
        [ 79.6266, 100.1607],
        [121.9550, 132.6272],
        [ 31.0331,  41.7389],
        [ 91.5363, 115.5469],
        [ 58.9063,  71.1603],
        [ 79.6266, 100.1607],
        [121.9550, 132.6272],
        [ 31.0331,  41.7389],
        [ 91.5363, 115.5469]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])